import type { GradeBand, WordEntry, WordTier } from "./types";

const k2Tier1 = [
  "cat",
  "dog",
  "sun",
  "run",
  "hop",
  "red",
  "big",
  "bug",
  "fox",
  "map",
  "bed",
  "cup",
  "hat",
  "jam",
  "kid",
  "log",
  "mud",
  "net",
  "pig",
  "web",
];

const k2Tier2 = [
  "apple",
  "happy",
  "green",
  "river",
  "funny",
  "penny",
  "plant",
  "smile",
  "chair",
  "cloud",
  "grass",
  "light",
  "truck",
  "water",
  "zebra",
  "bread",
  "clock",
  "dream",
  "snack",
  "story",
];

const k2Tier3 = [
  "animal",
  "basket",
  "castle",
  "dragon",
  "flower",
  "garden",
  "little",
  "market",
  "pencil",
  "planet",
  "purple",
  "rocket",
  "school",
  "silver",
  "window",
  "yellow",
];

const g35Tier1 = [
  "planet",
  "forest",
  "market",
  "rocket",
  "bridge",
  "castle",
  "summer",
  "winter",
  "animal",
  "stream",
  "branch",
  "bright",
  "circle",
  "danger",
  "energy",
  "friend",
  "growth",
  "island",
  "lesson",
  "number",
];

const g35Tier2 = [
  "adventure",
  "calendar",
  "creative",
  "describe",
  "explorer",
  "fraction",
  "gravity",
  "habitat",
  "imagine",
  "journey",
  "library",
  "machine",
  "neighbor",
  "pattern",
  "question",
  "respect",
  "science",
  "texture",
  "weather",
  "whisper",
];

const g35Tier3 = [
  "celebrate",
  "challenge",
  "community",
  "different",
  "discover",
  "estimate",
  "important",
  "invention",
  "knowledge",
  "multiply",
  "organize",
  "practice",
  "solution",
  "strategy",
  "treasure",
  "volcano",
];

const g68Tier1 = [
  "analyze",
  "ancient",
  "balance",
  "biology",
  "climate",
  "culture",
  "diagram",
  "eclipse",
  "evidence",
  "fiction",
  "history",
  "journal",
  "mixture",
  "network",
  "primary",
  "resource",
  "summary",
  "theorem",
  "variable",
  "writing",
];

const g68Tier2 = [
  "accurate",
  "argument",
  "chemical",
  "contrast",
  "currency",
  "database",
  "equation",
  "function",
  "generate",
  "heritage",
  "identify",
  "latitude",
  "metaphor",
  "organism",
  "parallel",
  "research",
  "sequence",
  "symmetry",
  "transfer",
  "velocity",
];

const g68Tier3 = [
  "adaptation",
  "atmosphere",
  "conclusion",
  "democracy",
  "ecosystem",
  "hypothesis",
  "inference",
  "literature",
  "migration",
  "perspective",
  "photosynthesis",
  "probability",
  "relationship",
  "significant",
  "transformation",
  "vocabulary",
];

export const WORD_BANK: WordEntry[] = [
  ...entries("k2", 1, k2Tier1),
  ...entries("k2", 2, k2Tier2),
  ...entries("k2", 3, k2Tier3),
  ...entries("g35", 1, g35Tier1),
  ...entries("g35", 2, g35Tier2),
  ...entries("g35", 3, g35Tier3),
  ...entries("g68", 1, g68Tier1),
  ...entries("g68", 2, g68Tier2),
  ...entries("g68", 3, g68Tier3),
];

export function getWordsForBand(band: GradeBand, maxTier: WordTier) {
  return WORD_BANK.filter((entry) => entry.band === band && entry.tier <= maxTier);
}

function entries(band: GradeBand, tier: WordTier, words: string[]): WordEntry[] {
  return words.map((word) => ({ band, tier, word: word.toLowerCase() }));
}
