import type { GradeBand, WordEntry, WordTier } from "./types";

// Word lists are grouped by grade band and difficulty tier. The choices lean on
// Science of Reading-friendly spelling practice: phoneme-grapheme mapping,
// short vowels, digraphs, blends, vowel teams, r-controlled vowels, syllables,
// affixes, roots, and morphology.
const k2Tier1 = [
  "cat",
  "dog",
  "sun",
  "run",
  "hop",
  "red",
  "big",
  "bug",
  "fox",
  "map",
  "bed",
  "cup",
  "hat",
  "jam",
  "kid",
  "log",
  "mud",
  "net",
  "pig",
  "web",
  "bag",
  "bat",
  "box",
  "can",
  "cap",
  "dot",
  "fan",
  "fin",
  "gum",
  "hen",
  "leg",
  "lip",
  "mop",
  "pan",
  "pet",
  "pin",
  "pot",
  "ram",
  "sip",
  "van",
];

const k2Tier2 = [
  "apple",
  "happy",
  "green",
  "river",
  "funny",
  "penny",
  "plant",
  "smile",
  "chair",
  "cloud",
  "grass",
  "light",
  "truck",
  "water",
  "zebra",
  "bread",
  "clock",
  "dream",
  "snack",
  "story",
  "ship",
  "shop",
  "fish",
  "dish",
  "chip",
  "chat",
  "thin",
  "path",
  "whale",
  "when",
  "slide",
  "brave",
  "stone",
  "shine",
  "train",
  "paint",
  "seed",
  "moon",
  "star",
  "corn",
];

const k2Tier3 = [
  "basket",
  "dragon",
  "flower",
  "garden",
  "little",
  "pencil",
  "purple",
  "school",
  "silver",
  "window",
  "yellow",
  "button",
  "butter",
  "candle",
  "carrot",
  "dinner",
  "kitten",
  "ladder",
  "letter",
  "mitten",
  "napkin",
  "pocket",
  "rabbit",
  "sandwich",
  "sister",
  "sudden",
  "turtle",
  "under",
  "winter",
  "zigzag",
  "crayon",
  "teacher",
];

const g35Tier1 = [
  "forest",
  "bridge",
  "summer",
  "stream",
  "branch",
  "bright",
  "circle",
  "danger",
  "energy",
  "friend",
  "growth",
  "island",
  "lesson",
  "number",
  "author",
  "charge",
  "choice",
  "corner",
  "double",
  "engine",
  "future",
  "gentle",
  "harvest",
  "insect",
  "jungle",
  "kernel",
  "length",
  "motion",
  "nature",
  "oxygen",
  "phrase",
  "quartz",
  "reason",
  "season",
  "signal",
  "timber",
  "unicorn",
  "valley",
  "wonder",
  "yonder",
];

const g35Tier2 = [
  "adventure",
  "calendar",
  "creative",
  "describe",
  "explorer",
  "fraction",
  "gravity",
  "habitat",
  "imagine",
  "journey",
  "library",
  "machine",
  "neighbor",
  "pattern",
  "question",
  "respect",
  "science",
  "texture",
  "weather",
  "whisper",
  "alphabet",
  "boundary",
  "captain",
  "decimal",
  "elastic",
  "fossil",
  "glacier",
  "healthy",
  "invent",
  "kingdom",
  "lantern",
  "measure",
  "notebook",
  "observe",
  "predict",
  "quality",
  "reflect",
  "surface",
  "thunder",
  "visitor",
];

const g35Tier3 = [
  "celebrate",
  "challenge",
  "community",
  "different",
  "discover",
  "estimate",
  "important",
  "invention",
  "knowledge",
  "multiply",
  "organize",
  "practice",
  "solution",
  "strategy",
  "treasure",
  "volcano",
  "agreement",
  "brilliant",
  "carefully",
  "direction",
  "education",
  "formation",
  "happiness",
  "incorrect",
  "movement",
  "pollution",
  "reaction",
  "sensible",
  "treatment",
  "vacation",
  "wildlife",
  "yesterday",
];

const g68Tier1 = [
  "analyze",
  "ancient",
  "balance",
  "biology",
  "climate",
  "culture",
  "diagram",
  "eclipse",
  "evidence",
  "fiction",
  "history",
  "journal",
  "mixture",
  "network",
  "primary",
  "resource",
  "summary",
  "theorem",
  "variable",
  "writing",
  "abstract",
  "archive",
  "caption",
  "context",
  "density",
  "dynamic",
  "element",
  "formula",
  "geology",
  "justice",
  "kinetic",
  "logical",
  "mineral",
  "nucleus",
  "organic",
  "precise",
  "qualify",
  "thermal",
  "uniform",
  "visible",
];

const g68Tier2 = [
  "accurate",
  "argument",
  "chemical",
  "contrast",
  "currency",
  "database",
  "equation",
  "function",
  "generate",
  "heritage",
  "identify",
  "latitude",
  "metaphor",
  "organism",
  "parallel",
  "research",
  "sequence",
  "symmetry",
  "transfer",
  "velocity",
  "absolute",
  "capacity",
  "criteria",
  "dominant",
  "external",
  "federal",
  "geometry",
  "interval",
  "judgment",
  "language",
  "molecule",
  "negative",
  "operator",
  "property",
  "reactionary",
  "specific",
  "taxonomy",
  "ultimate",
  "vertical",
  "workshop",
];

const g68Tier3 = [
  "adaptation",
  "atmosphere",
  "conclusion",
  "democracy",
  "ecosystem",
  "hypothesis",
  "inference",
  "literature",
  "migration",
  "perspective",
  "photosynthesis",
  "probability",
  "relationship",
  "significant",
  "transformation",
  "vocabulary",
  "acceleration",
  "biodiversity",
  "classification",
  "decomposition",
  "equilibrium",
  "generalization",
  "interdependence",
  "justification",
  "magnification",
  "neutralization",
  "photosphere",
  "quantitative",
  "representation",
  "specialization",
  "thermodynamics",
  "visualization",
];

export const WORD_BANK: WordEntry[] = [
  ...entries("k2", 1, k2Tier1),
  ...entries("k2", 2, k2Tier2),
  ...entries("k2", 3, k2Tier3),
  ...entries("g35", 1, g35Tier1),
  ...entries("g35", 2, g35Tier2),
  ...entries("g35", 3, g35Tier3),
  ...entries("g68", 1, g68Tier1),
  ...entries("g68", 2, g68Tier2),
  ...entries("g68", 3, g68Tier3),
];

export function getWordsForBand(band: GradeBand, maxTier: WordTier) {
  return WORD_BANK.filter((entry) => entry.band === band && entry.tier <= maxTier);
}

function entries(band: GradeBand, tier: WordTier, words: string[]): WordEntry[] {
  return words.map((word) => ({ band, tier, word: word.toLowerCase() }));
}
